name: keyhub_dart_sdk
description: Dart SDK for KeyHub
version: 0.0.1
publish_to: none
repository: https://github.com/topicuskeyhub/sdk-dart

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  microsoft_kiota_abstractions:
    git:
      url: https://github.com/kiota-community/dart_kiota.git
      ref: v0.0.2
      path: packages/microsoft_kiota_abstractions
  microsoft_kiota_http:    
    git:
      url: https://github.com/kiota-community/dart_kiota.git
      ref: v0.0.2
      path: packages/microsoft_kiota_http
  microsoft_kiota_serialization_json:
    git:
      url: https://github.com/kiota-community/dart_kiota.git
      ref: v0.0.2
      path: packages/microsoft_kiota_serialization_json
  http: ^1.2.2
  uuid: ^4.5.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
