name: keyhub_dart_sdk
description: Dart SDK for KeyHub
version: 0.0.1
publish_to: none
repository: https://github.com/topicuskeyhub/sdk-dart

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  microsoft_kiota_abstractions: ^0.1.0
  microsoft_kiota_http: ^0.0.7
  microsoft_kiota_serialization_json: ^0.0.7
  http: ^1.5.0
  uuid: ^4.5.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
