name: keyhub_dart_sdk
description: Dart SDK for KeyHub
version: 0.0.1
publish_to: none
repository: https://github.com/topicuskeyhub/sdk-dart

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  microsoft_kiota_abstractions: ^0.0.2
  microsoft_kiota_http: ^0.0.2
  microsoft_kiota_serialization_json: ^0.0.2
  http: ^1.2.2
  uuid: ^4.5.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
